name: charts_common
version: 0.4.0
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  collection: ^1.14.5
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1

dev_dependencies:
  mockito: ^3.0.0
  test: ^1.3.0
